Update markers module to stick to markers
bnx05/pytest-selenium pull request #10
Opened 2017-02-19 06:41 UTC by bnx05

renamed module as well

2017-02-21 03:56 UTC, marisaq2016 requested changes

2017-02-21 03:56 UTC, marisaq2016 commented on test_custom_markers.py
> +    def test_aeert_signup_input_field_type(self):
``aeert`` typo?

2017-02-21 10:33 UTC, bnx05 commented
@marisaq2016 updated

2017-02-24 01:37 UTC, marisaq2016 approved these changes
lgtm

2017-02-24 09:33 UTC, merged