Add separate module for skip and xfail tests
bnx05/pytest-selenium pull request #11
Opened 2017-02-19 06:43 UTC by bnx05

2017-02-21 03:34 UTC, marisaq2016 requested changes

2017-02-21 03:34 UTC, marisaq2016 commented on test_skip_xfail.py
> +@pytest.mark.xfail(reason="button is disabled")
I think it would be better if the skip and xfail in separate module.

2017-02-23 10:14 UTC, bnx05 commented
@marisaq2016 updated, please check

2017-02-24 01:36 UTC, marisaq2016 requested changes

2017-02-24 01:36 UTC, marisaq2016 commented on test_skip.py
> +@pytest.mark.skip(reason="reset password unavailable from navbar")
we already have reset password on start

2017-02-24 09:48 UTC, merged