Rearrange and fix test_assert_email_and_password_length test
bnx05/pytest-selenium pull request #12
Opened 2017-02-19 07:15 UTC by bnx05

2017-02-21 03:54 UTC, marisaq2016 requested changes

2017-02-21 03:54 UTC, marisaq2016 commented on test_parameters.py
> +def test_assert_login_button_enabled(email, password):
this test is no longer asserting the login button

2017-02-21 03:54 UTC, marisaq2016 commented on test_parameters.py
> +    pytest.mark.xfail("blah"),
can we remove ``xfail``?

2017-02-23 10:46 UTC, bnx05 commented
@marisaq2016  updated, please check

2017-02-23 10:49 UTC, marisaq2016 approved these changes
lgtm

2017-02-23 10:50 UTC, merged