Add comments to explain tests
bnx05/pytest-selenium pull request #13
Opened 2017-02-19 07:50 UTC by bnx05

2017-02-21 03:43 UTC, marisaq2016 requested changes

2017-02-21 03:43 UTC, marisaq2016 commented on test_fixtures.py
>      @pytest.mark.parametrize("email, password", [
maybe focus on fixture test only

2017-02-21 11:03 UTC, bnx05 commented
@marisaq2016 updated, please check

2017-02-23 12:23 UTC, marisaq2016 approved these changes
lgtm

2017-02-24 09:32 UTC, merged